# Визуализация в Pandas

### Подготовка к работе

In [1]:
# Импортируем необходимые библиотеки
import pandas as pd

In [3]:
# Загружаем данные в Pandas
wines = pd.read_csv('data/Red.csv').head(100)

### Просмотр данных
Сейчас мы попробуем получить самую необходимую инормацию о наших данных с помощью методов pandas.

In [4]:
# Смотрим на данные
wines.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016

Для того чтобы понимать что содержится внутри нашего датафрейма мы можем отобразить основные метрики: персентили, максимумы и минимумы, среднее значение и т.д.

In [5]:
# Посмотрим на числовые данные чуть подробнее
wines[['Rating', 'NumberOfRatings', 'Price', 'Year']].describe()

           Rating  NumberOfRatings       Price         Year
count  100.000000       100.000000  100.000000   100.000000
mean     3.860000       337.810000   34.464000  2015.240000
std      0.309773       401.635739   71.001396     2.674685
min      2.900000       100.000000    4.750000  2005.000000
25%      3.700000       100.750000    9.500000  2014.750000
50%      3.850000       101.000000   16.775000  2016.000000
75%      4.100000      1000.000000   31.375000  2017.000000
max      4.600000      1025.000000  633.620000  2019.000000

### Стилизация датафрейма
Pandas умеет отображать данные c использованием пользовательских настроек. Это может пригодиться для более удобного визуального анализа данных или для составления красивых отчётов.   
У параметра style много настроек, подробнее про него можно почитать в официальной документации: https://pandas.pydata.org/docs/user_guide/style.html

Как мы увидим ниже, style без настроек отобразит нам датафрейм почти в неизменном виде. 
Единственное отличие - дробные числа будут иметь гораздо больше знаков после запятой.

In [6]:
# Базовая стилизация
wines.style

Метод format позволяет нам настроить отображение данных. Таким образом мы вернём удобное для нас количество десятичных знаков.

In [ ]:
# Добавим форматирование, чтобы всё отображалось как раньше (используем классический синтаксис питона для форматирования строк)
wines.style.format(formatter={'Rating': "{:.1f}", 'Price': "{:.2f}"})

Нам вероятно захочется отметить некоторые особо примечательные значения в нашем датафреме. Для этого мы можем использовать встронные функции для наиболее популярных случаев или применить кастомное оформление.  
Подробнее о встроенных функциях можно почитать в документации: https://pandas.pydata.org/docs/reference/api/pandas.io.formats.style.Styler.html

In [7]:
# Здесь мы подсвечиваем максимальные значения во всех столбцах
wines.style.highlight_max(axis=0)

In [ ]:
# При помощи метода applymap мы можем задать намного более сложную подсветку на основе значений
def highlight_cols(val):
    if val < 200:
        color = 'red'
    elif val > 1000:
        color = 'green'
    else:
        color = None
    return 'background-color: %s' % color

wines.style.applymap(highlight_cols, subset=pd.IndexSlice[:, ['NumberOfRatings']])

### ПРАКТИКА (5 мин)

1. Добавить перед ценой (Price) знак доллара ($10.25)
2. Для столбца Year подсветить года в промежутке с 2010 по 2015
3. Для столбцов Country и Region подсветить синим все слова, которые содержат ровно 6 букв. Зелёным - те, в которых букв больше и красным - те, в которых букв меньше.

P.S. Смело используйте шпаргалку и документацию

In [ ]:
# Напишите здесь своё решение

### Pandas и Matplotlib
Pandas умеет строить графики на основе нашего датафрейма. "Под капотом" он использует Matplotlib. Такой способ подойдет нам для простейшей визуализации. Но для полноценной работы с графиками гораздо удобнее работать напрямую с matplotlib.   
Подробнее про визуализацию: https://pandas.pydata.org/docs/user_guide/visualization.html

In [ ]:
# Строим график с pandas
price = wines['Price']
price.plot()